import img1 from '../assets/EiffelTower.jpg'
import img2 from '../assets/LionHead.jpg'
import img3 from '../assets/Batman.jpeg'
import img4 from '../assets/KittySelfDefenceKeyChain.jpg' 
import img5 from '../assets/MakerFaireRobot.png'
import img6 from '../assets/Pii.jpeg'
import img7 from '../assets/totodile.png'
import img8 from '../assets/hippo.jpeg'
const FoodData = [
  {
    id: 1,
    img: img1,
    name: "Eiffel Tower",
    price: 200,
    desc: "",
    category: "Art",
    rating: 4.5,
  },
  {
    id: 2,
    img: img2,
    name: "Lion Head",
    price: 300,
    desc: "",
    category: "Art",
    rating: 4.2,
  },
  {
    id: 3,
    img: img3,
    name: "Batarang with batman letters",
    price: 160,
    desc: "",
    category: "Toy",
    rating: 4.6,
  },
  {
    id: 4,
    img: img4,
    name: "Kitty Self-Defence KeyChain",
    price: 140,
    desc: "",
    category: "Toy",
    rating: 4.2,
  },
  {
    id: 5,
    img: img5,
    name: "Maker Faire Robot Action Figure",
    price: 170,
    desc: "",
    category: "Model",
    rating: 4.8,
  },
  {
    id: 6,
    img: img6,
    name: "Tower of Pi",
    price: 500,
    desc: "",
    category: "Model",
    rating: 4.5,
  },
  {
    id: 7,
    img: img7,
    name: "Totodile (Poke'mon)",
    price: 110,
    desc: "",
    category: "Art",
    rating: 4.2,
  },
  {
    id: 8,
    img:img8,
    name: "Paste Pusher Hippo",
    price: 95,
    desc: "",
    category: "Model",
    rating: 4.1,
  },
  // {
  //   id: 9,
  //   img: "",
  //   name: "",
  //   price: 120,
  //   desc: "",
  //   category: "Toy",
  //   rating: 4.6,
  // },
  // {
  //   id: 10,
  //   img: "",
  //   name: "",
  //   price: 85,
  //   desc: "",
  //   category: "Model",
  //   rating: 4.5,
  // },
  // {
  //   id: 11,
  //   img: "",
  //   name: "",
  //   price: 190,
  //   desc: "",
  //   category: "Toy",
  //   rating: 4.5,
  // },
  // {
  //   id: 12,
  //   img: "",
  //   name: "",
  //   price: 160,
  //   desc: "",
  //   category: "Model",
  //   rating: 4.8,
  // },
  // {
  //   id: 13,
  //   img: "",
  //   name: "",
  //   price: 130,
  //   desc: "",
  //   category: "Art",
  //   rating: 4.2,
  // },
  // {
  //   id: 14,
  //   img: "",
  //   name: "",
  //   price: 160,
  //   desc: "",
  //   category: "Toy",
  //   rating: 4.6,
  // },
  // {
  //   id: 15,
  //   img: "",
  //   name: "",
  //   price: 175,
  //   desc: "",
  //   category: "Model",
  //   rating: 4.5,
  // },
  // {
  //   id: 16,
  //   img: "",
  //   name: "",
  //   price: 120,
  //   desc: "",
  //   category: "Art",
  //   rating: 4.3,
  // },
  // {
  //   id: 17,
  //   img: "",
  //   name: "",
  //   price: 130,
  //   desc: "",
  //   category: "Model",
  //   rating: 4.4,
  // },
  // {
  //   id: 18,
  //   img: "",
  //   name: "",
  //   price: 130,
  //   desc: "",
  //   category: "Toy",
  //   rating: 4.9,
  // },
  // {
  //   id: 19,
  //   img: "",
  //   name: "",
  //   price: 90,
  //   desc: "",
  //   category: "Model",
  //   rating: 4.4,
  // },
  // {
  //   id: 20,
  //   img: "",
  //   name: "",
  //   price: 70,
  //   desc: "",
  //   category: "Toy",
  //   rating: 4.8,
  // },
];
export default FoodData;
